//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockAvg
    {
        public int id { get; set; }
        public string code { get; set; }
        public double avgPrice { get; set; }
        public double highestPrice { get; set; }
        public double lowestPrice { get; set; }
        public int avgShares { get; set; }
        public double avgTurnover { get; set; }
    }
}
