//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockMemo
    {
        public int id { get; set; }
        public string code { get; set; }
        public string ext1 { get; set; }
        public string ext2 { get; set; }
        public string ext3 { get; set; }
        public string ext4 { get; set; }
        public string ext5 { get; set; }
        public string ext6 { get; set; }
        public string ext7 { get; set; }
        public string ext8 { get; set; }
        public string ext9 { get; set; }
        public string ext10 { get; set; }
        public string ext11 { get; set; }
        public string ext12 { get; set; }
        public string ext13 { get; set; }
        public string ext14 { get; set; }
        public string ext15 { get; set; }
        public string ext16 { get; set; }
    }
}
