//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockIndex
    {
        public int id { get; set; }
        public string type { get; set; }
        public string category { get; set; }
        public string code { get; set; }
        public string company { get; set; }
        public System.DateTime dataDate { get; set; }
        public bool isEnable { get; set; }
    }
}
