//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockProfit
    {
        public int id { get; set; }
        public string code { get; set; }
        public int operId { get; set; }
        public double buyPrice { get; set; }
        public int buyShares { get; set; }
        public double buyCost { get; set; }
        public double profit { get; set; }
        public double profitPercentage { get; set; }
    }
}
