//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysConfig
    {
        public int id { get; set; }
        public System.DateTime stockUpdate { get; set; }
        public System.DateTime otcUpdate { get; set; }
        public System.DateTime nowDate { get; set; }
        public System.DateTime avgStartDate { get; set; }
        public System.DateTime avgEndDate { get; set; }
    }
}
