//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysLog
    {
        public int id { get; set; }
        public string type { get; set; }
        public System.DateTime date { get; set; }
        public string message { get; set; }
    }
}
