//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStock.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebStockEntities : DbContext
    {
        public WebStockEntities()
            : base("name=WebStockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<member> member { get; set; }
        public DbSet<stockAvg> stockAvg { get; set; }
        public DbSet<stockData> stockData { get; set; }
        public DbSet<stockDataTmp> stockDataTmp { get; set; }
        public DbSet<stockDataTmpOtc> stockDataTmpOtc { get; set; }
        public DbSet<stockIndex> stockIndex { get; set; }
        public DbSet<stockNow> stockNow { get; set; }
        public DbSet<sysConfig> sysConfig { get; set; }
        public DbSet<sysLog> sysLog { get; set; }
    }
}
